import s from "../components/NavigationBlock/NavigationBlock.module.scss";

export const positions = [
  {
    title: "Услуги",
    xPos: 0,
    yPos: 1,
    className: s.nav_up,
    arrowFirstClass: s.arrow_up,
    arrowSecondClass: s.arrow_up,
  },
  {
    title: "Тарифы",
    xPos: 0,
    yPos: -1,
    className: s.nav_down,
    arrowFirstClass: s.arrow_down,
    arrowSecondClass: s.arrow_down,
  },
  {
    title: "В лево",
    xPos: 1,
    yPos: 0,
    className: s.nav_left,
    arrowFirstClass: s.arrow_left,
    arrowSecondClass: s.arrow_left,
  },
  {
    title: "Разработка сайтов",
    xPos: -1,
    yPos: 0,
    className: s.nav_right,
    arrowFirstClass: s.arrow_right,
    arrowSecondClass: s.arrow_right,
  },
  { title: "Центр", xPos: 0, yPos: 0 },
  {
    title: "Вверх лево",
    xPos: 1,
    yPos: 1,
    className: s.nav_up_left,
    arrowFirstClass: s.arrow_up_left,
    arrowSecondClass: s.arrow_up_left,
  },
  {
    title: "Контакты",
    xPos: -1,
    yPos: 1,
    className: s.nav_up_right,
    arrowFirstClass: s.arrow_up_right,
    arrowSecondClass: s.arrow_up_right,
  },
  {
    title: "Вниз лево",
    xPos: 1,
    yPos: -1,
    className: s.nav_down_left,
    arrowFirstClass: s.arrow_down_left,
    arrowSecondClass: s.arrow_down_left,
  },
  {
    title: "Вниз право",
    xPos: -1,
    yPos: -1,
    className: s.nav_down_right,
    arrowFirstClass: s.arrow_down_right,
    arrowSecondClass: s.arrow_down_right,
  },
];
